#
# (C) Copyright 2016 HP Development Company, L.P.
# Confidential computer software. Valid license from HP required for possession, use or copying.
# Consistent with FAR 12.211 and 12.212, Commercial Computer Software,
# Computer Software Documentation, and Technical Data for Commercial Items are licensed
# to the U.S. Government under vendor's standard commercial license.
#

# A rule to enable access to Apigee organization endpoints to all services
# see on https://istio.io/docs/tasks/traffic-management/egress.html

apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: hpcorp-cwp-dev.apigee-egress-rule
spec:
  destination:
    service: hpcorp-cwp-dev.apigee.net
  ports:
    - port: 443
      protocol: https
