apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: imager-canary
spec:
  destination:
    name: imager
  precedence: 1
  route:
  - labels:
      version:  0.0.1
    weight: 90
  - labels:
      version:  0.0.2
    weight: 10