
# A rule to enable access to httpbin services
# see on https://istio.io/docs/tasks/traffic-management/egress.html

apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: httpbin-egress-rule
spec:
  destination:
    service: now.httpbin.org
  ports:
    - port: 80
      protocol: http
